/* Configuración compartida de los maestros para los demos de ayuda */
export const ABM = {
    cliente: {
        singular: 'cliente', plural: 'clientes', icono: 'building',
        columnas: ['Código', 'Razón social', 'Provincia', 'Email', 'CUIT'],
        filas: [
            ['CLI-001', 'YPF S.A.',          'Buenos Aires', 'compras@ypf.com',         '30-54668997-9'],
            ['CLI-002', 'Techint Ingeniería', 'CABA',         'ing@techint.com',          '30-50007654-3'],
            ['CLI-003', 'Pampa Energía',      'Neuquén',      'admin@pampa.com.ar',       '30-67890123-4'],
            ['CLI-004', 'Tecpetrol',          'Salta',        'contacto@tecpetrol.com',   '30-71234567-1'],
        ],
        campos: [
            { label: 'Código', value: 'CLI-005', req: true, col: 3 },
            { label: 'Razón social', value: 'Nueva Empresa S.A.', req: true, col: 9 },
            { label: 'Nombre', value: 'Nueva Empresa', col: 6 },
            { label: 'CUIT', value: '30-12345678-9', col: 6 },
            { label: 'Provincia', value: 'Buenos Aires', tipo: 'select', col: 4 },
            { label: 'Localidad', value: 'San Isidro', col: 4 },
            { label: 'Dirección', value: 'Av. Libertador 1234', col: 4 },
            { label: 'Teléfono', value: '+54 11 4555-1234', col: 4 },
            { label: 'Email', value: 'contacto@nueva.com', col: 4 },
            { label: 'Logo', value: '— sin archivo —', tipo: 'file', col: 4 },
        ],
        nota: 'Los contactos se cargan en una sección aparte: nombre, cargo, teléfono y email. Pueden agregarse varios por cliente.',
    },
    comitente: {
        singular: 'comitente', plural: 'comitentes', icono: 'briefcase',
        columnas: ['Código', 'Nombre', 'CUIT', 'Provincia'],
        filas: [
            ['COM-01', 'Techint Ingeniería',  '30-50007654-3', 'CABA'],
            ['COM-02', 'SIAT - Tenaris',       '30-60012345-2', 'Buenos Aires'],
            ['COM-03', 'Skanska Argentina',    '30-67891234-5', 'CABA'],
        ],
        campos: [
            { label: 'Código', value: 'COM-04', req: true, col: 4 },
            { label: 'Nombre', value: 'Nuevo Comitente', req: true, col: 8 },
            { label: 'CUIT', value: '30-12345678-9', col: 6 },
            { label: 'Provincia', value: 'Buenos Aires', tipo: 'select', col: 6 },
        ],
    },
    usuario: {
        singular: 'usuario', plural: 'usuarios', icono: 'user',
        columnas: ['Usuario', 'Nombre completo', 'Email', 'Rol', 'Estado'],
        filas: [
            ['jperez',     'Juan Pérez',        'jperez@enod.com',     'Operador',    'Activo'],
            ['laguirre',   'Marcos Aguirre',    'maguirre@enod.com',   'Asistente',   'Activo'],
            ['lmendoza',   'Lucía Mendoza',     'lmendoza@enod.com',   'Inspector',   'Activo'],
            ['cliente.ypf','YPF Supervisor',    'sup@ypf.com',         'Cliente',     'Activo'],
            ['btest',      'Bruno Test',        'btest@enod.com',      'Sistemas',    'Suspendido'],
        ],
        campos: [
            { label: 'Usuario', value: 'nuevo.user', req: true, col: 4 },
            { label: 'Email', value: 'nuevo@enod.com', req: true, col: 8 },
            { label: 'Nombre', value: 'Nombre Apellido', col: 6 },
            { label: 'DNI', value: '30.123.456', col: 6 },
            { label: 'Rol', value: 'Operador', tipo: 'select', col: 6 },
            { label: 'Cliente asociado', value: '— ninguno —', tipo: 'select', col: 6 },
            { label: 'Contraseña', value: '••••••••', tipo: 'password', col: 6 },
            { label: 'Repetir contraseña', value: '••••••••', tipo: 'password', col: 6 },
        ],
        nota: 'Si el usuario es de cliente, se elige el cliente asociado. Si es interno, se asignan roles del sistema (Spatie).',
    },
    soldador: {
        singular: 'soldador', plural: 'soldadores', icono: 'fire',
        columnas: ['Código', 'Nombre', 'EPS habilitados', 'Procesos'],
        filas: [
            ['S-104', 'A. Gómez',   'EPS-API-1104 / EPS-ASME-IX', 'GTAW / SMAW'],
            ['S-118', 'M. Suárez',  'EPS-API-1104',                'SMAW'],
            ['S-122', 'C. Núñez',   'EPS-API-1104 (vencido)',      'SMAW'],
            ['S-130', 'R. Vargas',  'EPS-ASME-IX',                 'GTAW / FCAW'],
        ],
        campos: [
            { label: 'Código', value: 'S-146', req: true, col: 4 },
            { label: 'Nombre', value: 'Nuevo Soldador', req: true, col: 8 },
            { label: 'DNI', value: '32.555.111', col: 6 },
            { label: 'EPS habilitados', value: 'EPS-API-1104', tipo: 'select', col: 6 },
            { label: 'Procesos', value: 'GTAW, SMAW', col: 6 },
            { label: 'Vto. calificación', value: '15/12/2026', col: 6 },
        ],
    },
    equipo: {
        singular: 'equipo', plural: 'equipos', icono: 'wrench',
        columnas: ['Código', 'Tipo', 'Marca / modelo', 'Método'],
        filas: [
            ['EQ-RX-001', 'RX',              'Spellman SP-200',    'RI'],
            ['EQ-YU-002', 'Yugo',             'Magnaflux Y-7',      'PM'],
            ['EQ-US-003', 'Detector US',      'OmniScan MX2',       'US'],
            ['EQ-PA-004', 'Palpador',         'Olympus 2.25 MHz',   'US'],
        ],
        campos: [
            { label: 'Código', value: 'EQ-RX-005', req: true, col: 4 },
            { label: 'Tipo', value: 'RX', tipo: 'select', col: 4 },
            { label: 'Método', value: 'RI', tipo: 'select', col: 4 },
            { label: 'Marca', value: 'Spellman', col: 6 },
            { label: 'Modelo', value: 'SP-200', col: 6 },
            { label: 'Kv máx', value: '200', col: 4 },
            { label: 'mA máx', value: '5', col: 4 },
            { label: 'Tamaño foco (mm)', value: '0.8', col: 4 },
        ],
    },
    internoequipo: {
        singular: 'interno de equipo', plural: 'internos de equipos', icono: 'tag',
        columnas: ['N° interno', 'Equipo', 'Frente actual', 'Última verif.'],
        filas: [
            ['INT-0042', 'EQ-RX-001 (Spellman SP-200)', 'Obra NEA T12',     '10/06/2026'],
            ['INT-0118', 'EQ-YU-002 (Magnaflux Y-7)',    'CD Neuquén',       '02/06/2026'],
            ['INT-0207', 'EQ-US-003 (OmniScan MX2)',     'Planta Río III',   '20/05/2026'],
        ],
        campos: [
            { label: 'N° interno', value: 'INT-0208', req: true, col: 4 },
            { label: 'Equipo padre', value: 'EQ-RX-001', tipo: 'select', col: 8 },
            { label: 'Frente actual', value: 'CD Neuquén', tipo: 'select', col: 6 },
            { label: 'Fecha verificación', value: '25/06/2026', col: 6 },
        ],
    },
    fuente: {
        singular: 'fuente', plural: 'fuentes', icono: 'sun-o',
        columnas: ['Código', 'Isótopo', 'Actividad inicial', 'Fecha calibración'],
        filas: [
            ['FU-Ir-001', 'Ir-192', '100 Ci', '10/04/2026'],
            ['FU-Ir-002', 'Ir-192', '80 Ci',  '15/05/2026'],
            ['FU-Se-001', 'Se-75',  '50 Ci',  '20/03/2026'],
        ],
        campos: [
            { label: 'Código', value: 'FU-Ir-003', req: true, col: 4 },
            { label: 'Isótopo', value: 'Ir-192', tipo: 'select', col: 4 },
            { label: 'N° serie', value: 'IR-2026-007', col: 4 },
            { label: 'Actividad inicial', value: '100', col: 4 },
            { label: 'Unidad', value: 'Ci', tipo: 'select', col: 4 },
            { label: 'Fecha calibración', value: '25/06/2026', col: 4 },
        ],
    },
    internofuente: {
        singular: 'interno de fuente', plural: 'internos de fuente', icono: 'tag',
        columnas: ['N° interno', 'Fuente', 'Frente actual', 'Actividad actual'],
        filas: [
            ['INF-001', 'FU-Ir-001', 'Obra NEA T12',  '78.5 Ci'],
            ['INF-002', 'FU-Ir-002', 'CD Neuquén',     '65.2 Ci'],
        ],
        campos: [
            { label: 'N° interno', value: 'INF-003', req: true, col: 4 },
            { label: 'Fuente padre', value: 'FU-Ir-001', tipo: 'select', col: 8 },
            { label: 'Frente actual', value: 'CD Neuquén', tipo: 'select', col: 6 },
            { label: 'Actividad actual (Ci)', value: '78.5', col: 6 },
        ],
    },
    material: {
        singular: 'material', plural: 'materiales', icono: 'cube',
        columnas: ['Código', 'Descripción', 'Norma', 'Grupo P'],
        filas: [
            ['MAT-001', 'Acero al carbono A106 Gr.B',  'ASTM A106',   'P-1'],
            ['MAT-002', 'Acero inoxidable A312-304L',   'ASTM A312',   'P-8'],
            ['MAT-003', 'Acero baja aleación A335-P11', 'ASTM A335',   'P-4'],
        ],
        campos: [
            { label: 'Código', value: 'MAT-004', req: true, col: 4 },
            { label: 'Descripción', value: 'Acero al carbono A53', req: true, col: 8 },
            { label: 'Norma', value: 'ASTM A53', col: 6 },
            { label: 'Grupo P', value: 'P-1', tipo: 'select', col: 6 },
        ],
    },
    producto: {
        singular: 'producto', plural: 'productos', icono: 'cubes',
        columnas: ['Código', 'Descripción', 'Unidad'],
        filas: [
            ['P-001', 'Film radiográfico Kodak AA400',  '14×17"'],
            ['P-002', 'Revelador SKD-S2 aerosol',        '400 cm³'],
            ['P-003', 'Líquido penetrante SKL-SP',        '400 cm³'],
            ['P-004', 'Removedor SKC-S',                  '400 cm³'],
        ],
        campos: [
            { label: 'Código', value: 'P-005', req: true, col: 4 },
            { label: 'Descripción', value: 'Nuevo producto', req: true, col: 8 },
            { label: 'Unidad', value: '14×17"', tipo: 'select', col: 6 },
            { label: 'Stock mínimo', value: '10', col: 6 },
        ],
    },
    servicio: {
        singular: 'servicio', plural: 'servicios', icono: 'cog',
        columnas: ['Código', 'Descripción', 'Método', 'Unidad'],
        filas: [
            ['SRV-RI', 'Radiografía industrial',  'RI', 'placas'],
            ['SRV-PM', 'Partículas magnéticas',    'PM', 'metros'],
            ['SRV-LP', 'Líquidos penetrantes',     'LP', 'metros'],
            ['SRV-US', 'Ultrasonido',              'US', 'puntos'],
        ],
        campos: [
            { label: 'Código', value: 'SRV-CV', req: true, col: 4 },
            { label: 'Descripción', value: 'Inspección visual', req: true, col: 8 },
            { label: 'Método', value: 'CV', tipo: 'select', col: 6 },
            { label: 'Unidad', value: 'metros', tipo: 'select', col: 6 },
        ],
    },
    unidad: {
        singular: 'unidad', plural: 'unidades de medida', icono: 'balance-scale',
        columnas: ['Código', 'Descripción', 'Símbolo'],
        filas: [
            ['UN-001', 'Metro',                'm'],
            ['UN-002', 'Pulgada',               '"'],
            ['UN-003', 'Placa radiográfica',    'placa'],
            ['UN-004', 'Punto de medición',     'pto'],
        ],
        campos: [
            { label: 'Código', value: 'UN-005', req: true, col: 4 },
            { label: 'Descripción', value: 'Kilogramo', req: true, col: 5 },
            { label: 'Símbolo', value: 'kg', col: 3 },
        ],
    },
    medida: {
        singular: 'medida', plural: 'medidas', icono: 'arrows-h',
        columnas: ['Código', 'Descripción', 'Unidad'],
        filas: [
            ['MED-001', '14 × 17 pulgadas', '"'],
            ['MED-002', '10 × 12 pulgadas', '"'],
            ['MED-003', '6 m',              'm'],
            ['MED-004', '12 m',             'm'],
        ],
        campos: [
            { label: 'Código', value: 'MED-005', req: true, col: 4 },
            { label: 'Descripción', value: 'Nueva medida', req: true, col: 5 },
            { label: 'Unidad', value: '"', tipo: 'select', col: 3 },
        ],
    },
    documentacion: {
        singular: 'documentación', plural: 'documentaciones', icono: 'file-text-o',
        columnas: ['Código', 'Tipo', 'Descripción', 'Vto.'],
        filas: [
            ['DOC-001', 'Procedimiento', 'PR-RI-007 Radiografía DDSE',      '—'],
            ['DOC-002', 'ART',            'ART operador Juan Pérez',          '15/12/2026'],
            ['DOC-003', 'Certificación',  'Nivel II RI - A. Gómez',           '20/08/2027'],
            ['DOC-004', 'Habilitación',   'Habilitación ARN equipo RX-001',   '30/06/2027'],
        ],
        campos: [
            { label: 'Código', value: 'DOC-005', req: true, col: 4 },
            { label: 'Tipo', value: 'Procedimiento', tipo: 'select', col: 4 },
            { label: 'Vencimiento', value: '31/12/2027', col: 4 },
            { label: 'Descripción', value: 'Nueva documentación', col: 8 },
            { label: 'Archivo', value: '— sin archivo —', tipo: 'file', col: 4 },
        ],
    },
    norma: {
        singular: 'norma', plural: 'normas', icono: 'book',
        columnas: ['Código', 'Descripción', 'Tipo'],
        filas: [
            ['API 1104',  'Soldadura de ductos',                  'Fabricación'],
            ['ASME V',    'Ensayos no destructivos',               'Ensayo'],
            ['ASME IX',   'Calificación de procedimientos',         'Fabricación'],
            ['ASTM E94',  'Práctica recomendada de radiografía',    'Ensayo'],
        ],
        campos: [
            { label: 'Código', value: 'API 5L', req: true, col: 4 },
            { label: 'Descripción', value: 'Tubería para conducción', req: true, col: 8 },
            { label: 'Tipo', value: 'Fabricación', tipo: 'select', col: 6 },
            { label: 'Revisión', value: 'Ed. 2018', col: 6 },
        ],
    },
    rol: {
        singular: 'rol', plural: 'roles', icono: 'shield',
        columnas: ['Rol', 'Permisos asignados', 'Usuarios'],
        filas: [
            ['Sistemas',  '142 permisos (acceso total)',    '2 usuarios'],
            ['Operador',  '38 permisos (operativo + NDT)',  '12 usuarios'],
            ['Inspector', '24 permisos (consulta + firma)',  '5 usuarios'],
            ['Cliente',   '8 permisos (visualización)',       '18 usuarios'],
        ],
        campos: [
            { label: 'Nombre del rol', value: 'Nuevo rol', req: true, col: 6 },
            { label: 'Descripción', value: 'Descripción del rol', col: 6 },
        ],
        nota: 'Después de crear el rol, hay que ir a "Asignar permisos" y tildar los permisos que corresponden. Los roles se manejan con Spatie Permission.',
    },
};

export const ABM_KEYS = Object.keys(ABM);
