import Vue from 'vue';
export const eventNewRegistro = new Vue();
export const eventEditRegistro = new Vue();
export const eventSetReferencia = new Vue();
export const eventDeleteFile = new Vue();
export const eventEditHeaderInforme = new Vue();
export const eventHeaderParte = new Vue();
export const eventModal = new Vue();
const eventAlerta = new Vue();
export default eventAlerta;
